<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE personas [
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre+,apellido1,apellido2?,telefono*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
]>
<!-- 
+ 1 a n
? 0 || 1
* 0 a n
-->
<personas>
<persona>
<nombre>Rosa</nombre>
<nombre>Clara</nombre>
<apellido1>Casas</apellido1>
<apellido2>Rueda</apellido2>
</persona>
<persona>
<nombre>Sergio</nombre>
<apellido1>Fuentes</apellido1>
<apellido2>Rio</apellido2>
<telefono>911111111</telefono>
</persona>
<persona>
<nombre>Lorena</nombre>
<apellido1>Madrid</apellido1>
<telefono>912222222</telefono>
<telefono>601222222</telefono>
</persona>
</personas>
