<!DOCTYPE listalibros [
    <!ELEMENT listalibros (libro+)>
    <!ELEMENT libro (titulo,autor+,editorial,descripcion*,precio)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT editorial (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
]>
<listalibros>
    <libro>
        <titulo>photoshop 5.5</titulo>
        <autor>Micheal Karbo</autor>
        <autor>Peter g</autor>
        <editorial>PC cuadernos</editorial>
        <precio>4</precio>
    </libro>
    <libro>
        <titulo>cree su pagina web</titulo>
        <autor>Johanan</autor>
        <editorial>cuadernos</editorial>
        <descripcion>aprenda a crear su pagina web</descripcion>
        <precio>4</precio>
    </libro>
    <libro>
        <titulo>El registro de windows</titulo>
        <autor>David bosman</autor>
        <editorial>PC cuadernos</editorial>
        <descripcion>Trucos para editar el registro</descripcion>
        <precio>4</precio>
    </libro>
</listalibros>