=== ethane66/asir-2023/Marcas/XML/practica3_tema1.dtd
<!ELEMENT personas (persona+)>
    <!ELEMENT persona (nombre+, apellido1, apellido2?, telefono*, direccion)>
    <!ATTLIST persona nacionalidad CDATA #IMPLIED>
    <!ATTLIST persona sexo (hombre | mujer) "hombre">
    <!ATTLIST persona id_persona CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido1 (#PCDATA)>
    <!ELEMENT apellido2 (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT direccion (via, nombrevia, numero, piso?, puerta?, poblacion, ciudad)>
        <!ELEMENT via (#PCDATA)>
        <!ATTLIST via tipo (Calle | Avenida | Plaza) "Calle">
        <!ELEMENT nombrevia (#PCDATA)>
        <!ELEMENT numero (#PCDATA)>
        <!ELEMENT piso (#PCDATA)>
        <!ELEMENT puerta (#PCDATA)>
        <!ELEMENT poblacion (#PCDATA)>
        <!ATTLIST poblacion codigo CDATA #IMPLIED>
        <!ELEMENT ciudad (#PCDATA)>

=== ethane66/asir-2023/Marcas/XML/practica3_tema1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE personas SYSTEM "practica3_tema1.dtd">
<personas>
    <persona nacionalidad="española" sexo="mujer" id_persona="A1111">
        <nombre>Rosa</nombre>
        <nombre>Clara</nombre>
        <apellido1>Casas</apellido1>
        <apellido2>Rueda</apellido2>
        <direccion>
            <via tipo="Calle" />
            <nombrevia>Juncal</nombrevia>
            <numero>1</numero>
            <piso>1º</piso>
            <puerta>A</puerta>
            <poblacion codigo="28850">Torrejón de Ardoz</poblacion>
            <ciudad>Madrid</ciudad>
        </direccion>
    </persona>
    <persona sexo="hombre" id_persona="B2222">
        <nombre>Sergio</nombre>
        <apellido1>Fuentes</apellido1>
        <apellido2>Rio</apellido2>
        <telefono>911111111</telefono>
        <direccion>
            <via />
            <nombrevia>Londres</nombrevia>
            <numero>2</numero>
            <piso>2º</piso>
            <puerta>B</puerta>
            <poblacion codigo="28850">Torrejón de Ardoz</poblacion>
            <ciudad>Madrid</ciudad>
        </direccion>
    </persona>
    <persona nacionalidad="francesa" sexo="mujer" id_persona="C3333">
        <nombre>Lorena</nombre>
        <apellido1>Madrid</apellido1>
        <telefono>912222222</telefono>
        <telefono>601222222</telefono>
        <direccion>
            <via tipo="Avenida" />
            <nombrevia>Constitución</nombrevia>
            <numero>3</numero>
            <piso>3º</piso>
            <puerta>C</puerta>
            <poblacion codigo="28850">Torrejón de Ardoz</poblacion>
            <ciudad>Madrid</ciudad>
        </direccion>
    </persona>
    <persona id_persona="D4444">
        <nombre>Carlos</nombre>
        <apellido1>Flores</apellido1>
        <direccion>
            <via tipo="Plaza" />
            <nombrevia>Mayor</nombrevia>
            <numero>4</numero>
            <piso>4º</piso>
            <puerta>D</puerta>
            <poblacion codigo="28830">San Fernando de Henares</poblacion>
            <ciudad>Madrid</ciudad>
        </direccion>
    </persona>
</personas>
